### ISSUE TITLE
字段大小写问题

### ISSUE THREAD

**Issue by yuditxj** [ichensheng/TCDatabase#3]
在TCDatabaseDAO.m  807行的位置
NSDictionary *tableDef = [[self tablesDef] objectForKey:[self.table uppercaseString]];
    NSString *keyName = [[tableDef objectForKey:@"key"] uppercaseString];
这uppercaseString会有问题，如果字典里的key是小写的就会出现明明存在但是取不到值的问题，应该去掉uppercaseString

**Comment by ichensheng** [comment]
这里有一个约定，表定义的json里的key和字典里的key都要大写。
